# Generated by Django 5.1.1 on 2025-03-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Cliente'), (3, 'Vendedor')], default=2)),
            ],
        ),
    ]
