# Generated by Django 5.1.1 on 2025-03-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=254)),
                ('stock', models.IntegerField()),
                ('categoria', models.IntegerField(blank=True, choices=[(0, ''), (1, 'Moda'), (2, 'Tecnologia'), (3, 'Artesania'), (4, 'Accesorios'), (5, 'Servicios'), (6, 'Otros')], default=0, null=True)),
                ('color', models.IntegerField(blank=True, choices=[(0, 'Ninguno'), (1, 'Gris'), (2, 'Blanco'), (3, 'Negro'), (4, 'Amarillo'), (5, 'Azul'), (6, 'Rojo')], default=0, null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_sena.usuario')),
            ],
        ),
    ]
