# Generated by Django 5.1.1 on 2025-03-28 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0003_imagenproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cod',
        ),
    ]
