# Generated by Django 5.1.1 on 2025-03-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0004_remove_producto_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/'),
        ),
    ]
