# Generated by Django 5.1.1 on 2025-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0005_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contacto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='none', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(default='000000', max_length=20),
        ),
    ]
