# Generated by Django 5.1.1 on 2025-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0010_alter_usuario_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='certificado',
            field=models.ImageField(blank=True, null=True, upload_to='certificado/'),
        ),
    ]
