# Generated by Django 5.1.1 on 2025-04-26 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0013_remove_usuario_direccion_direccion_orden_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='certificado',
        ),
        migrations.CreateModel(
            name='SolicitudVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado', models.ImageField(blank=True, null=True, upload_to='certificado/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_sena.usuario')),
            ],
        ),
    ]
