# Generated by Django 5.1.1 on 2025-05-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0015_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
