# Generated by Django 4.2.6 on 2025-06-09 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0016_orden_estado_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('orden_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda_sena.ordenitem')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_sena.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_sena.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'producto', 'orden_item')},
            },
        ),
    ]
