# Generated by Django 5.1.6 on 2025-07-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0017_calificacionproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
