# Generated by Django 5.1.1 on 2025-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0018_usuario_codigo_verificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='es_principal',
            field=models.BooleanField(default=False, help_text='Imagen principal del producto'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen_original',
            field=models.ImageField(blank=True, help_text='Imagen original', null=True, upload_to='productos/originales/'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Miniatura 300x300', null=True, upload_to='productos/miniaturas/'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil_original',
            field=models.ImageField(blank=True, help_text='Imagen de perfil original', null=True, upload_to='usuarios/originales/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(help_text='Imagen optimizada en WebP', upload_to='productos/optimizadas/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de perfil optimizada', null=True, upload_to='usuarios/perfiles/'),
        ),
    ]
