# Generated by Django 5.1.6 on 2025-07-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0019_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo'),
        ),
    ]
