# Generated by Django 4.2.23 on 2025-07-07 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0020_usuario_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('slug', models.SlugField(help_text='URL amigable', max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional', null=True)),
                ('nivel', models.IntegerField(default=0, help_text='Nivel jerárquico (0=raíz)')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('activa', models.BooleanField(default=True, help_text='Categoría activa')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa', null=True, upload_to='categorias/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('padre', models.ForeignKey(blank=True, help_text='Categoría padre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tienda_sena.categoria')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nivel', 'orden', 'nombre'],
                'unique_together': {('padre', 'nombre')},
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda_sena.categoria'),
        ),
    ]
