# Generated by Django - Migración placeholder para resolver dependencias

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0020_usuario_activo'),
    ]

    operations = [
        # Esta migración no hace nada - es solo para satisfacer dependencias
        # La funcionalidad original fue revertida por 0022_revert_categoria_system
    ]
