# Generated by Django 5.1.1 on 2025-07-11 02:25

from django.db import migrations


def fix_categoria_constraints(apps, schema_editor):
    """
    Función para limpiar cualquier constraint residual de categorías
    """
    # Usar el schema_editor para ejecutar SQL directo si es necesario
    pass


def reverse_fix_categoria_constraints(apps, schema_editor):
    """
    Función de reversión (no hace nada)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0022_revert_categoria_system'),
    ]

    operations = [
        migrations.RunPython(
            fix_categoria_constraints,
            reverse_fix_categoria_constraints,
        ),
    ]
