# Generated by Django 5.1.6 on 2025-07-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0023_auto_20250710_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Ninguna'), (1, 'Electrónicos'), (2, 'Ropa'), (3, 'Hogar'), (4, 'Deportes'), (5, 'Libros'), (6, 'Juguetes'), (7, 'Automotriz'), (8, 'Salud y Belleza'), (9, 'Jardín'), (10, 'Herramientas')], default=0),
        ),
    ]
