# Generated by Django 4.2.23 on 2025-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0024_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(default='000000', max_length=20, unique=True),
        ),
    ]
