# Generated by Django 5.1.1 on 2025-07-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0024_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Notificación', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_leida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('success', 'Éxito'), ('warning', 'Advertencia'), ('error', 'Error'), ('pedido', 'Pedido'), ('vendedor', 'Vendedor'), ('sistema', 'Sistema')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default='Notificación', max_length=100),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
