# Generated by Django 5.1.1 on 2025-07-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0025_alter_notificacion_options_notificacion_fecha_leida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_envio',
            field=models.CharField(choices=[('estandar', 'Envío Estándar (3-5 días)'), ('express', 'Envío Express (1-2 días)'), ('recoger', 'Recoger en Tienda')], default='estandar', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales del cliente', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
