# Generated by Django 5.1.6 on 2025-07-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0026_orden_costo_envio_orden_metodo_envio_orden_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el producto está activo o deshabilitado'),
        ),
    ]
