# Generated by Django 4.2.23 on 2025-07-28 18:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0027_producto_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Productos'},
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='ID público en Cloudinary', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='cloudinary_version',
            field=models.CharField(blank=True, help_text='Versión en Cloudinary', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='imagen_cloudinary',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen almacenada en Cloudinary', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='usa_cloudinary',
            field=models.BooleanField(default=True, help_text='Si usa Cloudinary o almacenamiento local'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen optimizada local', null=True, upload_to='productos/optimizadas/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen_original',
            field=models.ImageField(blank=True, help_text='Imagen original local', null=True, upload_to='productos/originales/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='miniatura',
            field=models.ImageField(blank=True, help_text='Miniatura local', null=True, upload_to='productos/miniaturas/'),
        ),
    ]
