# Generated by Django 4.2.23 on 2025-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0028_alter_imagenproducto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_vendedor',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Confirmación'), ('confirmado', 'Confirmado por Vendedor'), ('preparando', 'Preparando Pedido'), ('listo', 'Listo para Envío'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el vendedor confirmó el pedido', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, help_text='Fecha de entrega', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, help_text='Fecha de envío', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_preparacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se inició la preparación', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='notas_vendedor',
            field=models.TextField(blank=True, help_text='Notas internas del vendedor', null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='numero_seguimiento',
            field=models.CharField(blank=True, help_text='Número de seguimiento del envío', max_length=100, null=True),
        ),
    ]
