# Generated by Django 4.2.23 on 2025-07-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0029_orden_estado_vendedor_orden_fecha_confirmacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='estado_vendedor',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_confirmacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha_preparacion',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='notas_vendedor',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='numero_seguimiento',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=10),
        ),
    ]
