# Generated by Django 4.2.23 on 2025-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0030_remove_orden_estado_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=10),
        ),
    ]
