# Generated by Django 5.1.6 on 2025-08-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0031_alter_orden_estado_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo_verificado',
            field=models.BooleanField(default=False, help_text='Indica si el correo electrónico ha sido verificado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_codigo_verificacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se generó el código de verificación', null=True),
        ),
    ]
