# Generated by Django 5.1.6 on 2025-08-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_sena', '0032_usuario_correo_verificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_codigo',
            field=models.CharField(blank=True, default='registro', help_text="Tipo de código: 'registro' o 'password'", max_length=20, null=True),
        ),
    ]
